name: CI/CD main flow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./vknewsclient

      - name: Build with Gradle
        run: ./gradlew assembleDebug
        working-directory: ./vknewsclient

      - name: Run Ktlint
        run: ./gradlew ktlintCheck
        working-directory: ./vknewsclient

      - name: Run Detekt
        run: ./gradlew detekt
        working-directory: ./vknewsclient

      - name: Run Unit Tests
        run: ./gradlew test
        working-directory: ./vknewsclient

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        working-directory: ./vknewsclient

      - name: Run UI Tests
        run: ./gradlew connectedCheck

      - name: Build APK
        run: ./gradlew assembleDebug
